// .opencode/skills/angular/templates/component-template.ts
/**
 * Angular Standalone Component Template
 *
 * Convenciones aplicadas:
 * - standalone: true
 * - ChangeDetectionStrategy.OnPush
 * - Estado local con signals (signal, computed)
 * - DI con inject()
 * - Inputs tipados con input.required<T>() / input<T>()
 * - Outputs tipados con output<T>()
 * - Template inline o templateUrl
 * - Estilos scoped con styleUrl o styles
 *
 * Uso: Copiar este archivo, renombrar la clase y selector,
 *       reemplazar los placeholders ({{ClassName}}, {{selector}}, etc.)
 */

import {
  Component,
  signal,
  computed,
  input,
  output,
  effect,
  ChangeDetectionStrategy,
  OnInit,
  OnDestroy,
  inject,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';

// --- Modelos de ejemplo (reemplazar con los reales) ---
interface {{ModelName}} {
  id: string;
  name: string;
  status: 'active' | 'inactive' | 'pending';
  createdAt: Date;
}

// --- Componente ---
@Component({
  selector: 'app-{{selector}}',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './{{file-name}}.component.html',
  styleUrl: './{{file-name}}.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class {{ClassName}}Component implements OnInit, OnDestroy {
  // --- Inputs (propiedades recibidas del padre) ---
  readonly item = input.required<{{ModelName}}>();
  readonly disabled = input(false);
  readonly variant = input<'default' | 'compact' | 'expanded'>('default');

  // --- Outputs (eventos emitidos al padre) ---
  readonly selected = output<{{ModelName}}>();
  readonly deleted = output<string>();
  readonly toggled = output<boolean>();

  // --- Estado local con signals ---
  private isExpanded = signal(false);
  private isHovered = signal(false);

  // --- Dependencias inyectadas ---
  // private someService = inject(SomeService);

  // --- Computed signals (derivadas del estado) ---
  readonly statusClass = computed(() => {
    const status = this.item().status;
    const classes: Record<string, string> = {
      active: 'status-active',
      inactive: 'status-inactive',
      pending: 'status-pending',
    };
    return classes[status] ?? 'status-unknown';
  });

  readonly cssClasses = computed(() => ({
    [this.statusClass()]: true,
    'is-expanded': this.isExpanded(),
    'is-hovered': this.isHovered(),
    'is-disabled': this.disabled(),
    [`variant-${this.variant()}`]: true,
  }));

  readonly displayName = computed(() => {
    const item = this.item();
    return item.name?.trim() || '(sin nombre)';
  });

  // --- Effect para side effects reactivos ---
  private _logEffect = effect(() => {
    // Se ejecuta cada vez que item() cambia
    const item = this.item();
    console.debug(`[{{ClassName}}] Item cargado: ${item.id}`);
  });

  // --- Lifecycle hooks ---
  ngOnInit(): void {
    // Inicialización que no depende del template
  }

  ngOnDestroy(): void {
    // Limpieza de recursos (aunque effects se limpian automáticamente)
  }

  // --- Métodos públicos (handlers del template) ---
  onSelect(): void {
    if (this.disabled()) return;
    this.selected.emit(this.item());
  }

  onToggle(): void {
    this.isExpanded.update(v => !v);
    this.toggled.emit(this.isExpanded());
  }

  onDelete(): void {
    this.deleted.emit(this.item().id);
  }

  onMouseEnter(): void {
    this.isHovered.set(true);
  }

  onMouseLeave(): void {
    this.isHovered.set(false);
  }

  // --- Métodos privados ---
  private logEvent(event: string): void {
    console.debug(`[{{ClassName}}] Evento: ${event}`, {
      itemId: this.item().id,
      timestamp: new Date().toISOString(),
    });
  }
}

// .opencode/skills/react/templates/component-template.tsx
/**
 * React Function Component Template
 *
 * Convenciones aplicadas:
 * - Function component tipado (sin clases)
 * - Estado local con useState
 * - Valores derivados con useMemo
 * - Efectos con useEffect (con cleanup)
 * - Props tipadas con interface
 * - Callbacks memoizados con useCallback cuando se pasan a hijos memoizados
 *
 * Uso: Copiar este archivo, renombrar el componente y el archivo,
 *       reemplazar los placeholders ({{ComponentName}}, {{ModelName}}, etc.)
 */

import { useCallback, useEffect, useMemo, useState } from 'react';

// --- Modelos de ejemplo (reemplazar con los reales) ---
interface {{ModelName}} {
  id: string;
  name: string;
  status: 'active' | 'inactive' | 'pending';
  createdAt: string;
}

// --- Props ---
interface {{ComponentName}}Props {
  item: {{ModelName}};
  disabled?: boolean;
  variant?: 'default' | 'compact' | 'expanded';
  onSelect: (item: {{ModelName}}) => void;
  onDelete: (id: string) => void;
  onToggle?: (expanded: boolean) => void;
}

// --- Componente ---
export function {{ComponentName}}({
  item,
  disabled = false,
  variant = 'default',
  onSelect,
  onDelete,
  onToggle,
}: {{ComponentName}}Props) {
  // --- Estado local ---
  const [isExpanded, setIsExpanded] = useState(false);
  const [isHovered, setIsHovered] = useState(false);

  // --- Valores derivados (computed) ---
  const statusClass = useMemo(() => {
    const classes: Record<string, string> = {
      active: 'status-active',
      inactive: 'status-inactive',
      pending: 'status-pending',
    };
    return classes[item.status] ?? 'status-unknown';
  }, [item.status]);

  const cssClasses = useMemo(
    () =>
      [
        statusClass,
        isExpanded && 'is-expanded',
        isHovered && 'is-hovered',
        disabled && 'is-disabled',
        `variant-${variant}`,
      ]
        .filter(Boolean)
        .join(' '),
    [statusClass, isExpanded, isHovered, disabled, variant]
  );

  const displayName = useMemo(() => item.name?.trim() || '(sin nombre)', [item.name]);

  // --- Efecto de logging (equivalente a un signal effect) ---
  useEffect(() => {
    console.debug(`[{{ComponentName}}] Item cargado: ${item.id}`);
  }, [item.id]);

  // --- Handlers memoizados ---
  const handleSelect = useCallback(() => {
    if (disabled) return;
    onSelect(item);
  }, [disabled, onSelect, item]);

  const handleToggle = useCallback(() => {
    setIsExpanded((prev) => {
      const next = !prev;
      onToggle?.(next);
      return next;
    });
  }, [onToggle]);

  const handleDelete = useCallback(() => {
    onDelete(item.id);
  }, [onDelete, item.id]);

  return (
    <div
      className={cssClasses}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
    >
      <h3>{displayName}</h3>
      <button onClick={handleSelect} disabled={disabled}>Select</button>
      <button onClick={handleToggle}>{isExpanded ? 'Collapse' : 'Expand'}</button>
      <button onClick={handleDelete}>Delete</button>
    </div>
  );
}
